theme: jekyll-theme-primer
title: Support Vector Olives
description: Keeping Italian Olives Pure!
baseurl: /gpages-master
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
